baseURL = "https://blog.anarcher.dev/"
languageCode = "en-us"
title = "Anarcher's Trashcan"
canonifyurls = true
copyright="&copy; 2019. All rights reserved."
theme = "yinyang"
Paginate = 5
enableRobotsTXT = true
googleAnalytics = "UA-38571523-1"
DefaultContentLanguage = "en"

[author]
name = "Anarcher"
homepage = "https://blog.anarcher.dev/"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
  [languages.ko]
    languageName = "Korean"
    weight = 2

[params]
[[params.socials]]
name = "About"
link = "/about"
[[params.socials]]
name = "Github"
link = "https://github.com/anarcher"
[[params.socials]]
name = "Twitter"
link = "https://twitter.com/anarcher"
[[params.socials]]
name = "Email"
link = "mailto:anarcher@gmail.com"
